from . import topics
courses = [
    {
        "_id":"2",
        "imageUrl":"https://res.cloudinary.com/idrs/image/upload/v1647436901/project3-ironhack/nqtp5mpimuspxxiau00j.png",
        "category":"Development",
        "difficultyLevel":"All levels",
        "description":"""The following content has been generated by our machine learning. We are continuously improving"
                        its efficiency. Your feedback is valued""",
        "whatYouWillLearn":["data science toolkits","natural language processing","machine learning algorithms",],
        "price": '10',
        "requirements":["Laptop\nInternet Connection",],
        "topics": topics.topics,
        "title":"React - The Complete Guide",
        "lead":"Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!",
        "duration": '10',
        "owner": 'author',
    }
]