# Generated by Django 4.0.3 on 2022-05-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_category_course_goaltoachieve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='job',
            new_name='jobRequired',
        ),
    ]
