# Generated by Django 4.0.3 on 2022-05-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_job_course_jobrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
