# Generated by Django 4.0.3 on 2022-05-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
