# Generated by Django 4.0.3 on 2022-05-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_topic_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dailyTime',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='goalToAchieve',
            new_name='name',
        ),
    ]
