# Generated by Django 4.0.3 on 2022-05-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_topic_note_googlelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlelink',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlelink',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='base.topic'),
        ),
    ]
